version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: $POSTGRES_DB_USER
      POSTGRES_PASSWORD: $POSTGRES_DB_PASSWORD
      POSTGRES_DB: $POSTGRES_DB_NAME
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  keydb:
    image: eqalpha/keydb:latest
    command: keydb-server --appendonly yes
    volumes:
      - ./keydb_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  producer:
    build: .
    command: producer
    init: true
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app_network
    env_file:
      - .env

  receiver:
    build: .
    command: receiver
    init: true
    depends_on:
      - postgres
      - rabbitmq
      - producer
      - key_db
    networks:
      - app_network
    env_file:
      - .env

  updater:
    build: .
    command: updater
    init: true
    depends_on:
      - postgres
      - key_db
      - receiver
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:
